# frozen_string_literal: true

require_relative '../lib/rag_pipeline'

RSpec.describe RagPipeline do
  let(:hits) do
    [
      { id: 1, score: 0.92, payload: { text: 'Trinta dias de férias por ano.', source: 'politica.txt' } },
      { id: 2, score: 0.81, payload: { text: 'Divisíveis em três períodos.', source: 'ferias.txt' } }
    ]
  end
  let(:retriever) { FakeRetriever.new(results: hits) }
  let(:llm) { FakeLlm.new }

  subject(:rag) { described_class.new(retriever: retriever, llm: llm, collection: 'documentos') }

  describe '#answer' do
    it 'retrieves the passages for the question' do
      rag.answer('Quantos dias de férias?')

      expect(retriever.calls.last).to include(query: 'Quantos dias de férias?', collection: 'documentos')
    end

    it 'retrieves top_k passages' do
      described_class.new(retriever: retriever, llm: llm, collection: 'documentos', top_k: 1)
                     .answer('Quantos dias de férias?')

      expect(retriever.calls.last[:limit]).to eq(1)
    end

    it 'sends a prompt containing the retrieved passages to the model' do
      rag.answer('Quantos dias de férias?')

      expect(llm.prompts.last).to include('Trinta dias de férias por ano.').and include('Divisíveis em três períodos.')
    end

    it 'returns the answer generated by the model' do
      expect(rag.answer('Quantos dias de férias?')[:answer]).to eq('Trinta dias por ano [1].')
    end

    it 'returns the sources used, without repetition' do
      repeated = FakeRetriever.new(results: hits + [{ id: 3, payload: { text: 'outro', source: 'politica.txt' } }])
      result = described_class.new(retriever: repeated, llm: llm, collection: 'documentos').answer('Pergunta')

      expect(result[:sources]).to eq(%w[politica.txt ferias.txt])
    end

    it 'returns the passages that grounded the answer' do
      expect(rag.answer('Quantos dias de férias?')[:passages].map { |p| p[:source] })
        .to eq(%w[politica.txt ferias.txt])
    end

    it 'forwards the metadata filter to the retriever' do
      filter = { must: [{ key: 'autor', match: { value: 'joao' } }] }

      rag.answer('Pergunta', filter: filter)

      expect(retriever.calls.last[:filter]).to eq(filter)
    end

    context 'when nothing is retrieved' do
      let(:retriever) { FakeRetriever.new(results: []) }

      it 'does not call the model, to avoid spending tokens' do
        rag.answer('Pergunta sem contexto')

        expect(llm.prompts).to be_empty
      end

      it 'answers that it does not know' do
        expect(rag.answer('Pergunta sem contexto')[:answer]).to eq(described_class::NO_CONTEXT_ANSWER)
      end

      it 'returns no sources' do
        expect(rag.answer('Pergunta sem contexto')[:sources]).to be_empty
      end
    end

    # O recuperador devolve o top-k por construção, por pior que seja o melhor.
    # Sem piso, "o menos ruim" era tratado como "o certo" e a API respondia
    # sobre férias uma pergunta de plano odontológico, citando a origem.
    context 'quando nada recuperado tem a ver com a pergunta' do
      subject(:rag) do
        described_class.new(retriever: retriever, llm: llm, collection: 'documentos',
                            relevance_floor: RelevanceFloor.new)
      end

      it 'refuses instead of answering with the least bad passage' do
        expect(rag.answer('qual o prazo do aviso prévio')[:answer]).to eq(described_class::NO_CONTEXT_ANSWER)
      end

      it 'does not spend a model call on it' do
        rag.answer('qual o prazo do aviso prévio')

        expect(llm.prompts).to be_empty
      end

      # Recusar citando origem seria pior do que responder errado: daria ao
      # "não encontrei" a aparência de estar apoiado em documento.
      it 'cites nothing' do
        expect(rag.answer('qual o prazo do aviso prévio')[:sources]).to be_empty
      end

      it 'still answers the question the corpus does cover' do
        expect(rag.answer('quantos dias de férias')[:answer]).to eq('Trinta dias por ano [1].')
      end

      # O piso corta trecho a trecho, não tudo ou nada: o que sobra é contexto
      # menor e mais limpo, não contexto nenhum.
      it 'drops only the passages that do not belong' do
        expect(rag.answer('quantos dias de férias')[:sources]).to eq(['politica.txt'])
      end
    end

    # Sem piso configurado o comportamento é o de antes, porque desligar
    # observabilidade e salvaguarda tem de continuar possível.
    it 'answers with whatever came back when there is no floor' do
      expect(rag.answer('qual o prazo do aviso prévio')[:sources]).not_to be_empty
    end

    it 'ignores hits without text in the payload' do
      partial = FakeRetriever.new(results: [{ id: 1, payload: { source: 'vazio.txt' } }] + hits)
      result = described_class.new(retriever: partial, llm: llm, collection: 'documentos').answer('Pergunta')

      expect(result[:sources]).not_to include('vazio.txt')
    end
  end

  describe 'com re-ranking' do
    let(:pool_hits) do
      [
        { id: 1, score: 0.91, payload: { text: 'texto sem relação nenhuma', source: 'a.txt' } },
        { id: 2, score: 0.90, payload: { text: 'trinta dias de férias por ano', source: 'b.txt' } }
      ]
    end
    let(:retriever) { FakeRetriever.new(results: pool_hits) }

    subject(:rag) do
      described_class.new(retriever: retriever, llm: llm, collection: 'documentos',
                          top_k: 1, reranker: Reranker.new)
    end

    it 'retrieves a bigger pool than top_k, to give the reranker what to choose from' do
      rag.answer('dias de férias')

      expect(retriever.calls.last[:limit]).to be > 1
    end

    it 'keeps only top_k passages after reranking' do
      expect(rag.answer('dias de férias')[:passages].size).to eq(1)
    end

    it 'promotes the passage that actually answers the question' do
      expect(rag.answer('dias de férias')[:sources]).to eq(['b.txt'])
    end

    it 'without a reranker, keeps the retrieval order' do
      plain = described_class.new(retriever: retriever, llm: llm, collection: 'documentos', top_k: 1)

      expect(plain.answer('dias de férias')[:sources]).to eq(['a.txt'])
    end
  end

  describe 'contagem de tokens' do
    it 'reports the tokens spent on the prompt and on the answer' do
      usage = rag.answer('Quantos dias de férias?')[:usage]

      expect(usage[:prompt_tokens]).to be > 0
      expect(usage[:completion_tokens]).to be > 0
      expect(usage[:total_tokens]).to eq(usage[:prompt_tokens] + usage[:completion_tokens])
    end

    it 'reports zero when the model is not called' do
      empty = described_class.new(retriever: FakeRetriever.new(results: []), llm: llm, collection: 'documentos')

      expect(empty.answer('sem contexto')[:usage][:total_tokens]).to eq(0)
    end
  end

  describe 'compressão do contexto' do
    subject(:rag) do
      described_class.new(retriever: retriever, llm: llm, collection: 'documentos',
                          compressor: PromptCompressor.new, context_budget: 8)
    end

    it 'fits the context into the budget' do
      counter = TokenCounter.new
      passages = rag.answer('Quantos dias de férias?')[:passages]

      expect(passages.sum { |passage| counter.estimate(passage[:text]) }).to be <= 8
    end

    it 'sends the compressed context to the model' do
      rag.answer('Quantos dias de férias?')

      expect(llm.prompts.last).not_to include('Divisíveis em três períodos.')
    end

    it 'without a compressor, sends every retrieved passage' do
      plain = described_class.new(retriever: retriever, llm: llm, collection: 'documentos')
      plain.answer('Quantos dias de férias?')

      expect(llm.prompts.last).to include('Divisíveis em três períodos.')
    end
  end

  # Instrumentação nasce desligada: o tracer padrão é o nulo, então nada muda
  # para quem não pediu observabilidade.
  describe 'tracing' do
    let(:exporter) { CollectingExporter.new }
    let(:tracer) { Tracer.new(exporter: exporter) }

    subject(:rag) do
      described_class.new(retriever: retriever, llm: llm, collection: 'documentos', tracer: tracer)
    end

    it 'exports one trace per question' do
      rag.answer('Quantos dias de férias?')

      expect(exporter.traces.size).to eq(1)
    end

    it 'records the question as the input of the trace' do
      rag.answer('Quantos dias de férias?')

      expect(exporter.last[:input]).to eq('Quantos dias de férias?')
    end

    # É o que se quer ver no gráfico: onde foi o tempo, na busca ou no modelo.
    it 'separates retrieval from generation' do
      rag.answer('Quantos dias de férias?')

      expect(exporter.last[:spans].map { |span| span[:name] }).to eq(%w[rag.retrieve rag.generate])
    end

    it 'records the token usage on the generation span' do
      rag.answer('Quantos dias de férias?')

      generation = exporter.last[:spans].last

      expect(generation[:usage][:total_tokens]).to be_positive
    end

    it 'keeps the generated answer as the output of the generation span' do
      rag.answer('Quantos dias de férias?')

      expect(exporter.last[:spans].last[:output]).to eq('Trinta dias por ano [1].')
    end

    # Sem contexto o modelo não é chamado, e o trace precisa mostrar isso: um
    # span de geração que não existiu é a explicação da latência baixa.
    it 'opens no generation span when there was no context to answer from' do
      empty = described_class.new(retriever: FakeRetriever.new(results: []), llm: llm,
                                  collection: 'documentos', tracer: tracer)
      empty.answer('Quantos dias de férias?')

      expect(exporter.last[:spans].map { |span| span[:name] }).to eq(['rag.retrieve'])
    end

    it 'does not change the answer' do
      traced = rag.answer('Quantos dias de férias?')
      plain = described_class.new(retriever: retriever, llm: llm, collection: 'documentos')
                             .answer('Quantos dias de férias?')

      expect(traced[:answer]).to eq(plain[:answer])
    end
  end

  # Os tokens no painel eram sempre estimativa, mesmo com um modelo que informa
  # o que cobrou. A escolha é por capacidade, não por classe: quem sabe
  # informar informa, quem não sabe continua estimado -- o `FakeLlm`, como o
  # `ExtractiveLlm`, não sabe.
  describe 'de onde vem a contagem de tokens' do
    let(:medido) { { prompt_tokens: 412, completion_tokens: 37, total_tokens: 449, measured: true } }

    def usage_from(model)
      described_class.new(retriever: retriever, llm: model, collection: 'documentos')
                     .answer('Quantos dias de férias?')[:usage]
    end

    it 'prefers what the provider reported over the estimate' do
      informante = Class.new do
        def initialize(usage) = @usage = usage
        def complete(prompt) = complete_with_usage(prompt).first
        def complete_with_usage(_prompt) = ['Trinta dias por ano [1].', @usage]
      end

      expect(usage_from(informante.new(medido))).to eq(medido)
    end

    it 'marks the estimate as an estimate when the model cannot report' do
      expect(usage_from(FakeLlm.new)).to include(measured: false)
    end

    # Modelo que sabe informar mas cuja resposta veio sem contagem: a
    # estimativa volta a valer, e diz que é estimativa.
    it 'falls back to the estimate when the reported usage is missing' do
      calado = Class.new do
        def complete(prompt) = complete_with_usage(prompt).first
        def complete_with_usage(_prompt) = ['Trinta dias por ano [1].', nil]
      end

      expect(usage_from(calado.new)).to include(measured: false)
    end
  end
end
