# frozen_string_literal: true

require_relative '../lib/rag_pipeline'

RSpec.describe RagPipeline do
  let(:hits) do
    [
      { id: 1, score: 0.92, payload: { text: 'Trinta dias de férias por ano.', source: 'politica.txt' } },
      { id: 2, score: 0.81, payload: { text: 'Divisíveis em três períodos.', source: 'ferias.txt' } }
    ]
  end
  let(:retriever) { FakeRetriever.new(results: hits) }
  let(:llm) { FakeLlm.new }

  subject(:rag) { described_class.new(retriever: retriever, llm: llm, collection: 'documentos') }

  describe '#answer' do
    it 'retrieves the passages for the question' do
      rag.answer('Quantos dias de férias?')

      expect(retriever.calls.last).to include(query: 'Quantos dias de férias?', collection: 'documentos')
    end

    it 'retrieves top_k passages' do
      described_class.new(retriever: retriever, llm: llm, collection: 'documentos', top_k: 1)
                     .answer('Quantos dias de férias?')

      expect(retriever.calls.last[:limit]).to eq(1)
    end

    it 'sends a prompt containing the retrieved passages to the model' do
      rag.answer('Quantos dias de férias?')

      expect(llm.prompts.last).to include('Trinta dias de férias por ano.').and include('Divisíveis em três períodos.')
    end

    it 'returns the answer generated by the model' do
      expect(rag.answer('Quantos dias de férias?')[:answer]).to eq('Trinta dias por ano [1].')
    end

    it 'returns the sources used, without repetition' do
      repeated = FakeRetriever.new(results: hits + [{ id: 3, payload: { text: 'outro', source: 'politica.txt' } }])
      result = described_class.new(retriever: repeated, llm: llm, collection: 'documentos').answer('Pergunta')

      expect(result[:sources]).to eq(%w[politica.txt ferias.txt])
    end

    it 'returns the passages that grounded the answer' do
      expect(rag.answer('Quantos dias de férias?')[:passages].map { |p| p[:source] })
        .to eq(%w[politica.txt ferias.txt])
    end

    it 'forwards the metadata filter to the retriever' do
      filter = { must: [{ key: 'autor', match: { value: 'joao' } }] }

      rag.answer('Pergunta', filter: filter)

      expect(retriever.calls.last[:filter]).to eq(filter)
    end

    context 'when nothing is retrieved' do
      let(:retriever) { FakeRetriever.new(results: []) }

      it 'does not call the model, to avoid spending tokens' do
        rag.answer('Pergunta sem contexto')

        expect(llm.prompts).to be_empty
      end

      it 'answers that it does not know' do
        expect(rag.answer('Pergunta sem contexto')[:answer]).to eq(described_class::NO_CONTEXT_ANSWER)
      end

      it 'returns no sources' do
        expect(rag.answer('Pergunta sem contexto')[:sources]).to be_empty
      end
    end

    it 'ignores hits without text in the payload' do
      partial = FakeRetriever.new(results: [{ id: 1, payload: { source: 'vazio.txt' } }] + hits)
      result = described_class.new(retriever: partial, llm: llm, collection: 'documentos').answer('Pergunta')

      expect(result[:sources]).not_to include('vazio.txt')
    end
  end
end
